### ISSUE TITLE
Shipyard consul server creation is stuck

### ISSUE THREAD

**Issue by pmmukh** [hashicorp/consul-service-mesh-for-developers#2]
Hi! A year late to the party, just stumbled on this repo from https://www.youtube.com/watch?v=gRpgyHfLQBI&list=PLmD8u-IFdrexJ8SlO_NcBm6nr0lQhRwZk&index=8.

When I run Shipyard with just `yard up`, then everything works perfectly.
However, when I use the `consul-values.yaml` linked here, it looks like the setup is getting stuck on the Consul server.

This is what the yard startup log looks like ( I bailed after ~15 mins )
<img width="1241" alt="Screen Shot 2021-05-23 at 9 27 18 AM" src="https://user-images.githubusercontent.com/35388175/119264496-14564f80-bba9-11eb-8fb4-a943339a7c76.png">

And the shipyard.log file goes up to the consul bit then has only these lines `No resources found in default namespace.`
<img width="656" alt="Screen Shot 2021-05-23 at 9 28 35 AM" src="https://user-images.githubusercontent.com/35388175/119264537-423b9400-bba9-11eb-914d-74fcfe204a3e.png">

I've never dealt with consul before, just testing the waters, so any hints on how I can debug this would be awesome!

**Comment by pmmukh** [comment]
Closing this one out actually, just noticed an issue for this already exists on the shipyard repo https://github.com/nicholasjackson/shipyard/issues/21, which is probably the place to talk about this

**Comment by nicholasjackson** [comment]
Hey, @pmmukh apologies about the lateness for replying, this repo is quite out of date at the moment, we actually migrated Shipyard to a new repo https://github.com/shipyard-run/shipyard quite a while ago. I am guessing that the other version is incompatible with the current Helm chart and Consul.

I have been meaning to update this content for some time, if you would bare with me a few weeks, I will update and refresh all this content. I would also like to add canary deployments.

Kind regards,

Nic

**Comment by pmmukh** [comment]
Hey Nic! No worries at all, thanks for getting back to me! 
Ah I did not know about the new repo, shall be sure to check it out. And can definitely come back and run through these tutorials later once you've had the chance to update them, I'm only idly messing around and am in no hurries whatsoever. Also canary deployments would certainly be a super neat topic for a tutorial, will keep my eyes peeled for that!
